### PR TITLE
Update resource structure

### PR DESCRIPTION
**Pull request by rabauss**
Update the structure of the resource 
This PR is based on #30

### CODE REVIEW

**Comment by m-vo** [comment]
Rebased on current HEAD.

**Comment by m-vo** [comment]
THis PR is only moving files. I don't see the benefit tbh.

**Comment by rabauss** [comment]
I don't like this "old" `Resource` structure - with this PR you get faster access to the files of `Resource`.
But if you don't like - we can also delete it 🤔

**Comment by m-vo** [comment]
Don't get me wrong: I prefer this for new projects as well. But it's just a convention that's not worth the trouble changing to IMHO.

**Pull request closed without merging**
