### PR TITLE
Raise GRAPH_API_VERSION to 7.0 for avoiding FB errors

### PR DESCRIPTION
**Pull request by trcwebdesign**
Facebook needs to queried by v7.0 for the page-id/posts and page-id/events endpoints. 
Older versions will display an error like this
error": {
    "message": "(m-vo#10) This endpoint requires the 'manage_pages' or 'pages_read_engagement' permission or the 'Page Public Content Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages and https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS for details.",
    "type": "OAuthException",
    "code": 10,

### CODE REVIEW

**Comment by m-vo** [comment]
Are you telling me that even though we're jumping 4 major versions ahead we do not need to adapt anything? :smile: 

Did you look through the changelogs? https://developers.facebook.com/docs/graph-api/changelog

@rabauss Do you already have some experience with this?

**Comment by m-vo** [comment]
@trcwebdesign From what I understand from the docs, the current extension should not break, should it? 

That said, I'm open for an update if this doesn't bring any side effects.

**Comment by fritzmg** [comment]
In our extension we had to change the following things, to be compatible with the current API versions:

* Change the permissions from `manage_pages, publish_pages` to `pages_read_engagement, pages_manage_posts`.
* When querying Facebook Page Posts, change the endpoint from `/posts` to `/published_posts`.

These changes should be compatible with all API versions starting from `3.0`, afaik.

**Comment by trcwebdesign** [comment]
> @trcwebdesign From what I understand from the docs, the current extension should not break, should it?
> 
> That said, I'm open for an update if this doesn't bring any side effects.

The FB change is breaking currently a lot of sites :
https://www.google.com/search?q=pages_read_engagement

**Comment by rabauss** [comment]
Well, I only have one customer who has not yet been able to give me access to his facebook page, and I thought it was no longer possible to import content from public pages without permission :-)

For customers, on whose facebook page I am also an administrator, there is no error as described above. I've seen the error logs only for those without authorization since one week!

**Comment by m-vo** [comment]
Thanks you all for your feedback.

The changes + some related fixes are implemented in v3.2.0.

**Pull request closed without merging**
